### ISSUE TITLE
Add support for @use

### ISSUE THREAD

**Issue by GianlucaGuarini** [nirazul/gulp-sass-globi#1]
What do you think about adding support for the  [`@use`](https://sass-lang.com/documentation/at-rules/use) rule?

I might have a look at it doing a PR.

**Comment by nirazul** [comment]
@GianlucaGuarini 
I would welcome a PR and implement it. However, I don't think that globbing for scss files is a good practice anymore. With `@use` it doesn't make even less sense, as you might want to use advanced syntax, i.e. renaming the module in place (`@use './a' as 'b'`) or forwarding it (`@forward`). The plugin doesn't prevent that but it's certainly inhibiting advanced usage of the `@use` at rule.

**Comment by GianlucaGuarini** [comment]
jep the implementation can be quite tricky and unintuitive. I am going to close this issue, I agree:  `I don't think that globbing for scss files is a good practice anymore,`
